### ISSUE TITLE
Error Uploading .zip in Siberian

### ISSUE THREAD

**Issue by Tatandiaz13** [Xtraball/enterprise-payment#1]
Hello,

I download the .zip from Siberian marketplace and I tried upload in my siberian backoffice but the  upload  return the next error:

> #19-010: The package you have uploaded is invalid.

any idea ?

Thanks.

**Comment by SiberianCMS** [comment]
The warning says "This is a development module, please do no install in a production environment."

This is not to install, it's only for development purposes.

The module from the marketplace should work, if not, contact the team at contact@siberiancms.com
